name: client
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  json_annotation: ^4.7.0
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  provider: ^6.0.4
  flutter_svg: ^1.1.6
  sizer: ^2.0.15
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  shimmer_animation: ^2.1.0+1
  modal_bottom_sheet: ^2.1.2
  flutter_secure_storage: ^4.2.1
  dropdown_button2: ^1.9.2
  flutter_holo_date_picker: ^1.1.0
  infinite_scroll_pagination: ^3.2.0
  rxdart: ^0.27.7
  smooth_page_indicator: ^1.0.0+2
  image_picker: ^0.8.6+1
  cross_file: ^0.3.3+4
  permission_handler: ^9.0.2
  image_cropper: ^3.0.0
  loading_animation_widget: ^1.2.0+4
  http_parser: ^4.0.2
  flutter_sticky_header: ^0.6.5
  sqflite: ^2.0.3+1
  path_provider: ^2.0.14
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  freezed: ^2.3.2

flutter:
  uses-material-design: true